ports:
  - port: 8080
    onOpen: open-preview
checkoutLocation: /go/src/github.com/aaqaishtyaq/planb
workspaceLocation: /go/src/github.com/aaqaishtyaq/planb
image:
  file: .gitpod.Dockerfile
vscode:
  extensions:
    - golang.go
    - eamodio.gitlens

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/44_config_start_tasks/
tasks:
- init: |
    bash /go/src/github.com/aaqaishtyaq/planb/entrypoint &
