FROM golang:1.11.13

RUN apt-get update && apt-get install -y vim git redis-server syslog-ng && \
    curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh && \
    mkdir -p /go/src/github.com/aaqaishtyaq


WORKDIR /go/src/github.com/aaqaishtyaq/planb

COPY ["entrypoint", "/entrypoint"]

ENTRYPOINT ["/entrypoint"]
